apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "com.tencent.shadow.sample.plugin"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 10
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.create("release")
            signingConfig.initWith(buildTypes.debug.signingConfig)
        }
    }

    // 将插件applicationId设置为和宿主相同
    productFlavors {
        plugin {
            applicationId "com.caet.asapp"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    //Shadow Transform后业务代码会有一部分实际引用runtime中的类
    //如果不以compileOnly方式依赖，会导致其他Transform或者Proguard找不到这些类
    //pluginCompileOnly "com.tencent.shadow.core:runtime:$shadow_version"
    pluginCompileOnly "com.tencent.shadow.core:runtime:2.2.1"
    //注意caet-host-lib要用compileOnly编译而不打包在插件中。在packagePlugin任务中配置hostWhiteList允许插件访问宿主的类。
    pluginCompileOnly project(':caet-host-lib')
    normalImplementation project(':caet-host-lib')

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation "org.java-websocket:Java-WebSocket:1.4.0"
    implementation 'com.google.code.gson:gson:2.9.1'


    //最新请求权限的框架
    implementation 'com.github.getActivity:XXPermissions:12.8'

    //GSYVideoPlayer用了core:1.7.0但是项目中用到的是1.5.0所以这里必须强制统一使用1.6.0
    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core:1.6.0'
        }
    }


}

//这段buildscript配置的dependencies是为了apply plugin: 'com.tencent.shadow.plugin'能找到实现
buildscript {
    repositories {
        if (!System.getenv().containsKey("DISABLE_TENCENT_MAVEN_MIRROR")) {
            maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        } else {
            google()
            mavenCentral()
        }
        maven {
            name = "GitHubPackages"
            url "https://maven.pkg.github.com/tencent/shadow"
            //一个只读账号兼容Github Packages暂时不支持匿名下载
            //https://github.community/t/download-from-github-package-registry-without-authentication/14407
            credentials {
                username = 'readonlypat'
                password = '\u0067hp_s3VOOZnLf1bTyvHWblPfaessrVYyEU4JdNbs'
            }
        }
        mavenLocal()
    }

    dependencies {
        //classpath "com.tencent.shadow.core:gradle-plugin:$shadow_version"
        classpath "com.tencent.shadow.core:gradle-plugin:2.2.1"
    }
}

shadow {
    packagePlugin {
        pluginTypes {
            debug {
                loaderApkConfig = new Tuple2('caet-loader-debug.apk', ':caet-loader:assembleDebug')
                runtimeApkConfig = new Tuple2('caet-runtime-debug.apk', ':caet-runtime:assembleDebug')
                pluginApks {
                    pluginApk1 {
                        businessName = 'plugin-one'//businessName相同的插件，context获取的Dir是相同的。businessName留空，表示和宿主相同业务，直接使用宿主的Dir。
                        partKey = 'plugin-one'
                        buildTask = 'assemblePluginDebug'
                        apkName = 'plugin-app-plugin-debug.apk'
                        apkPath = 'plugin-app/build/outputs/apk/plugin/debug/plugin-app-plugin-debug.apk'
                        hostWhiteList = ["com.caet.shadow.sample.host.lib"]
                    }
                }
            }

            release {
                loaderApkConfig = new Tuple2('caet-loader-release.apk', ':caet-loader:assembleRelease')
                runtimeApkConfig = new Tuple2('caet-runtime-release.apk', ':caet-runtime:assembleRelease')
                pluginApks {
                    pluginApk1 {
                        // 【businessName】是业务名称。Shadow允许一个Loader同时加载多个插件。只要这些插件没有so库冲突，这些插件可以是完全不相关的业务的。
                        // Shadow通过ClassLoader设计保证了多插件间Java类是隔离的，但是没法为Native的so库划出单独的内存空间。
                        // 除了代码有可能冲突，对data目录的使用也是有可能冲突的。因为Shadow的原理是“插件是宿主代码的一部分”，
                        // 所以所有插件都可以访问宿主的data目录。如果插件和宿主或者多插件之间有使用相同的data目录逻辑，
                        // 比如MultiDex会向一个固定的SharePreference持久化数据，就会出现持久化数据的冲突。为了解决这个问题，
                        // 引入的businessName。当businessName为空时，Shadow就认为这个插件跟宿主是同一个业务，这个插件直接使用宿主的data目录。
                        // 当businessName设置了值时，Shadow就会在宿主的data目录中以businessName为参数新建一个子目录作为插件的data根目录使用。
                        // 这样相同businessName的插件就会使用同一个data目录了，不同businessName的插件的data目录就相当于是隔离的了
                        businessName = 'plugin-one'
                        //是插件apk的别名。因为插件apk的文件名是有可能因为带了版本号或者什么参数而变化，所以有这样一个partKey作为一个插件apk的不变的别名。
                        // partKey可以用于在表示一个插件依赖另外一个插件时使用。Shadow内部在实现区分多插件逻辑时也会用partKey作为该apk的Key。
                        // 在Loader等接口上的partKey参数指的也是这个partKey
                        partKey = 'plugin-one'
                        buildTask = 'assemblePluginRelease'
                        apkName = 'plugin-app-plugin-release.apk'
                        apkPath = 'plugin-app/build/outputs/apk/plugin/release/plugin-app-plugin-release.apk'
                        //配置当前的插件可以访问宿主的那些类，默认情况下插件不能访问宿主的类
                        //【注意】宿主访问插件里面的类比较麻烦
                        hostWhiteList = ["com.caet.shadow.sample.host.lib"]
                    }
                }
            }
        }

        loaderApkProjectPath = 'caet-loader'
        runtimeApkProjectPath = 'caet-runtime'

        //version表示的是该config.json文件采用的格式版本；
        version = 4

        //compact_version表示的是当前config.json文件跟哪些格式的旧版本是兼容的，可以被支持旧版本格式的Manager使用。
        compactVersion = [1, 2, 3]

        // UUID表示的是插件包内容的版本，只有相同UUID的apk才能一同工作。apk有3中类型：Loader、Runtime、Plugin。
        // 所以在同一个config.json中描述的的所有apk都具有相同的UUID，所以能一同工作。UUID是要按照一般UUID生成算法生成的，
        // 以保证多次发布的插件版本不会重复。UUID_NickName则是一般业务使用的版本名，对插件更新逻辑没有实际作用。
        //
        // 需要注意的是，多个config.json是可以采用同一个UUID的。因为我们有时需要分段下载插件包，下载一部分先启动一部分。
        // 所以可以将插件apk分到多个config.json中，采用相同的UUID。并且，Loader和Runtime只需要存在于其中一个插件包中就可以了。
        uuid="E6592E15-B9F7-4D06-8D54-858CF3C2C364"

        //UUID_NickName则是一般业务使用的版本名，对插件更新逻辑没有实际作用。
        uuidNickName = "1.0.0"

        //修改打包出来的名字  buildTypes的前缀 debug/release
        archivePrefix = 'one'
        //修改打包出来的名字  buildTypes的后缀 debug/release
        archiveSuffix = ''
        //修改打包出来的名字  zip的输出路径
        destinationDir = "${getRootProject().getBuildDir()}"

        //复制到本地的adb命令
        //adb push build/one-debug.zip /data/local/tmp
        //adb push build/one-release.zip /data/local/tmp
        //adb push build/one.zip /data/local/tmp


    }
}
